# Generated by Django 3.2.17 on 2023-02-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Marca/Fabricante')),
            ],
            options={
                'verbose_name': 'Marca/Fabricante',
                'verbose_name_plural': 'Marcas/Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cor')),
                ('color_id', models.CharField(max_length=100, verbose_name='Código Cor')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição do produto')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('status', models.BooleanField(default=True, verbose_name='Disponível')),
                ('stock', models.PositiveIntegerField(verbose_name='Estoque disponível')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.brand', verbose_name='Marca/Fabricante')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.category', verbose_name='Categoria')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.color', verbose_name='Cor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.size', verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
